// Generated by gencpp from file autoturtle/AddTwoInts.msg
// DO NOT EDIT!


#ifndef AUTOTURTLE_MESSAGE_ADDTWOINTS_H
#define AUTOTURTLE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <autoturtle/AddTwoIntsRequest.h>
#include <autoturtle/AddTwoIntsResponse.h>


namespace autoturtle
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace autoturtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autoturtle::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::autoturtle::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::autoturtle::AddTwoInts > {
  static const char* value()
  {
    return "autoturtle/AddTwoInts";
  }

  static const char* value(const ::autoturtle::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::autoturtle::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::autoturtle::AddTwoInts >
template<>
struct MD5Sum< ::autoturtle::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autoturtle::AddTwoInts >::value();
  }
  static const char* value(const ::autoturtle::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autoturtle::AddTwoIntsRequest> should match
// service_traits::DataType< ::autoturtle::AddTwoInts >
template<>
struct DataType< ::autoturtle::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::autoturtle::AddTwoInts >::value();
  }
  static const char* value(const ::autoturtle::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autoturtle::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::autoturtle::AddTwoInts >
template<>
struct MD5Sum< ::autoturtle::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autoturtle::AddTwoInts >::value();
  }
  static const char* value(const ::autoturtle::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autoturtle::AddTwoIntsResponse> should match
// service_traits::DataType< ::autoturtle::AddTwoInts >
template<>
struct DataType< ::autoturtle::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::autoturtle::AddTwoInts >::value();
  }
  static const char* value(const ::autoturtle::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOTURTLE_MESSAGE_ADDTWOINTS_H
