// Generated by gencpp from file autoturtle/TeleportTurtleRequest.msg
// DO NOT EDIT!


#ifndef AUTOTURTLE_MESSAGE_TELEPORTTURTLEREQUEST_H
#define AUTOTURTLE_MESSAGE_TELEPORTTURTLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoturtle
{
template <class ContainerAllocator>
struct TeleportTurtleRequest_
{
  typedef TeleportTurtleRequest_<ContainerAllocator> Type;

  TeleportTurtleRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  TeleportTurtleRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TeleportTurtleRequest_

typedef ::autoturtle::TeleportTurtleRequest_<std::allocator<void> > TeleportTurtleRequest;

typedef boost::shared_ptr< ::autoturtle::TeleportTurtleRequest > TeleportTurtleRequestPtr;
typedef boost::shared_ptr< ::autoturtle::TeleportTurtleRequest const> TeleportTurtleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator1> & lhs, const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator1> & lhs, const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoturtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa130bc60ee651385ULL;
  static const uint64_t static_value2 = 0x5dc62ea83fcc5b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoturtle/TeleportTurtleRequest";
  }

  static const char* value(const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
"\n"
;
  }

  static const char* value(const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleportTurtleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoturtle::TeleportTurtleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoturtle::TeleportTurtleRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOTURTLE_MESSAGE_TELEPORTTURTLEREQUEST_H
