// Generated by gencpp from file autoturtle/TeleportTurtle.msg
// DO NOT EDIT!


#ifndef AUTOTURTLE_MESSAGE_TELEPORTTURTLE_H
#define AUTOTURTLE_MESSAGE_TELEPORTTURTLE_H

#include <ros/service_traits.h>


#include <autoturtle/TeleportTurtleRequest.h>
#include <autoturtle/TeleportTurtleResponse.h>


namespace autoturtle
{

struct TeleportTurtle
{

typedef TeleportTurtleRequest Request;
typedef TeleportTurtleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportTurtle
} // namespace autoturtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autoturtle::TeleportTurtle > {
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::autoturtle::TeleportTurtle&) { return value(); }
};

template<>
struct DataType< ::autoturtle::TeleportTurtle > {
  static const char* value()
  {
    return "autoturtle/TeleportTurtle";
  }

  static const char* value(const ::autoturtle::TeleportTurtle&) { return value(); }
};


// service_traits::MD5Sum< ::autoturtle::TeleportTurtleRequest> should match
// service_traits::MD5Sum< ::autoturtle::TeleportTurtle >
template<>
struct MD5Sum< ::autoturtle::TeleportTurtleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autoturtle::TeleportTurtle >::value();
  }
  static const char* value(const ::autoturtle::TeleportTurtleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autoturtle::TeleportTurtleRequest> should match
// service_traits::DataType< ::autoturtle::TeleportTurtle >
template<>
struct DataType< ::autoturtle::TeleportTurtleRequest>
{
  static const char* value()
  {
    return DataType< ::autoturtle::TeleportTurtle >::value();
  }
  static const char* value(const ::autoturtle::TeleportTurtleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autoturtle::TeleportTurtleResponse> should match
// service_traits::MD5Sum< ::autoturtle::TeleportTurtle >
template<>
struct MD5Sum< ::autoturtle::TeleportTurtleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autoturtle::TeleportTurtle >::value();
  }
  static const char* value(const ::autoturtle::TeleportTurtleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autoturtle::TeleportTurtleResponse> should match
// service_traits::DataType< ::autoturtle::TeleportTurtle >
template<>
struct DataType< ::autoturtle::TeleportTurtleResponse>
{
  static const char* value()
  {
    return DataType< ::autoturtle::TeleportTurtle >::value();
  }
  static const char* value(const ::autoturtle::TeleportTurtleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOTURTLE_MESSAGE_TELEPORTTURTLE_H
