// Generated by gencpp from file autoturtle/TeleportTurtleResponse.msg
// DO NOT EDIT!


#ifndef AUTOTURTLE_MESSAGE_TELEPORTTURTLERESPONSE_H
#define AUTOTURTLE_MESSAGE_TELEPORTTURTLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoturtle
{
template <class ContainerAllocator>
struct TeleportTurtleResponse_
{
  typedef TeleportTurtleResponse_<ContainerAllocator> Type;

  TeleportTurtleResponse_()
    {
    }
  TeleportTurtleResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TeleportTurtleResponse_

typedef ::autoturtle::TeleportTurtleResponse_<std::allocator<void> > TeleportTurtleResponse;

typedef boost::shared_ptr< ::autoturtle::TeleportTurtleResponse > TeleportTurtleResponsePtr;
typedef boost::shared_ptr< ::autoturtle::TeleportTurtleResponse const> TeleportTurtleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace autoturtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::autoturtle::TeleportTurtleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoturtle/TeleportTurtleResponse";
  }

  static const char* value(const ::autoturtle::TeleportTurtleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::autoturtle::TeleportTurtleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleportTurtleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoturtle::TeleportTurtleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::autoturtle::TeleportTurtleResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AUTOTURTLE_MESSAGE_TELEPORTTURTLERESPONSE_H
