(cl:defpackage autoturtle-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "TELEPORTTURTLE"
   "<TELEPORTTURTLE-REQUEST>"
   "TELEPORTTURTLE-REQUEST"
   "<TELEPORTTURTLE-RESPONSE>"
   "TELEPORTTURTLE-RESPONSE"
  ))

